version: "3.9"

services:
  service:
    build: .
    restart: unless-stopped
    pull_policy: build
    environment:
      - REDIS_HOST=redis
    networks:
      - zassets
    depends_on:
      - redis
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "${SERVER_PORT:-3000}:${FASTIFY_PORT:-3000}"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - zassets
    volumes:
      - redis_data:/data

networks:
  zassets:
    driver: overlay
    attachable: true
    internal: true

volumes:
  redis_data:
