version: "3.9"

services:
  service:
    build: .
    restart: unless-stopped
    pull_policy: build
    environment:
      - REDIS_HOST=redis
    ports:
      - "${SERVER_PORT:-3000}:${FASTIFY_PORT:-3000}"
    networks:
      - zassets
      - public
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - zassets

networks:
  zassets:
    driver: overlay
    attachable: true
    internal: true
  public:
    driver: overlay

volumes:
  redis_data:
