version: "3.9"

services:
  service:
    image: ghcr.io/zaralx/zaralx-assets:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    ports:
      - "${SERVER_PORT:-3000}:${FASTIFY_PORT:-3000}"
    networks:
      - zassets
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - zassets

networks:
  zassets:
    driver: bridge

volumes:
  redis_data: